<a href="https://colab.research.google.com/github/Lavanya-S-code/ML-lab-exp/blob/main/NUMPY_LIBRARY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 CREATING AN ARRAY BY USING LIST


In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

<class 'numpy.ndarray'>


CREATING AN ARRAY BY USING TUPLE

In [3]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


CREATING AN ARRAY IN TWO DIMENSIONAL


In [5]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


CREATING AN ARRAY IN TWO MATRIX TWO DIMENSIONAL


In [7]:
import numpy as np
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


TO CHECK THE DIMENSIONAL OF THE ARRAY


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print("Dimension of the array:",arr.ndim)


[1 2 3 4 5]
Dimension of the array: 1


TO CHECK THE DIMENSIONAL OF THE ARRAY

In [16]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("Dimension of the array:",arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension of the array: 2


In [20]:
import numpy as np
a=np.array([42])
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
d=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
e=np.array([])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

1
1
2
3
1


TO FIND OUT THE MEAN OF AN ARRAY

In [17]:
import numpy as np
arr=np.mean([1,2,3,4,5])
print("Mean of the array",arr)

Mean of the array 3.0


TO ACCESS THE ELEMENT OF AN ARRAY


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2])

3


ADDITION OF AN ARRAY

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("Addition of an array",arr[0]+arr[1])

Addition of an array 3
